services:
  vllm:
    image: vllm/vllm-openai:v0.28.0
    container_name: vllm
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
    volumes:
      - ./model_cache:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
    ports:
      - "8000:8000"
    ipc: host
    command:
      - --api-key
      - ${API_KEY}
      - --model
      - ${MODEL_NAME}
      - --quantization
      - awq
      - --gpu-memory-utilization
      - ${GPU_UTILIZE}
      - --max-model-len
      - ${MODEL_NUM_CTX}
      - --dtype
      - half
      - --max-num-batched-tokens
      - ${MODEL_NUM_CTX}
      - --kv-cache-dtype
      - ${KV_CACHE_DTYPE}
